"""Add is_read to Notification

Revision ID: e958ea1f970b
Revises: 4a48115b3060
Create Date: 2025-06-25 20:55:56.618711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e958ea1f970b'
down_revision = '4a48115b3060'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attendance_staff_fk'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['staff_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_notification_recipient'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_notification_sender'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'])
        batch_op.drop_column('read')

    with op.batch_alter_table('schedule_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('schedule_request_staff_fk'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['staff_id'], ['id'])

    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('shift_staff_fk'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['staff_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shift', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('shift_staff_fk'), 'user', ['staff_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('schedule_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('schedule_request_staff_fk'), 'user', ['staff_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_notification_sender'), 'user', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_notification_recipient'), 'user', ['recipient_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('is_read')

    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attendance_staff_fk'), 'user', ['staff_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
